#!/bin/bash
#SBATCH --partition=analysis
#SBATCH --ntasks=1
#SBATCH --tasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --output=pism.%j
#SBATCH --mem=214G

cd $SLURM_SUBMIT_DIR

ulimit -l unlimited
ulimit -s unlimited
ulimit


# Generated by /import/c1/ICESHEET/aaschwanden/pism-gris/stability/lhs_ensemble.py
# Command: ./lhs_ensemble.py -e ../latin_hypercube/lhs_control.csv --o_dir 2017_12_ctrl --exstep 1 -n 360 -w 168:00:00 -g 900 -s chinook -q t2standard --step 1000 --duration 1000 ../calibration/2017_06_vc/state/gris_g900m_flux_v3a_no_bath_sia_e_1.25_sia_n_3_ssa_n_3.25_ppq_0.6_tefo_0.02_calving_vonmises_calving_0_100.nc
# Git top level: /import/c1/ICESHEET/aaschwanden/pism-gris
# URL: git@github.com:pism/pism-gris.git
# Version: db18be3

# stop if a variable is not defined
set -u
# stop on errors
set -e

odir=2017_12_ctrl
grid=900
mkdir -p $odir/spatial_processed
mkdir -p $odir/ice_extend_vol
rcp=45
cdo -L selvar,mask -selyear,2056,2097,2189,2321,2665,3234 $odir/spatial/ex_g${grid}m_v3a_rcp_${rcp}_id_CTRL_0_3000.nc $odir/spatial_processed/ex_g${grid}m_v3a_rcp_${rcp}_id_CTRL_0_3000_percent.nc
extract_interface.py -a 1e6 -t grounding_line -o $odir/ice_extend/gl_ex_g900m_v3a_rcp_${rcp}_id_CTRL_percent.shp $odir/spatial_processed/ex_g${grid}m_v3a_rcp_${rcp}_id_CTRL_0_3000_percent.nc
