#!/bin/bash
#SBATCH --partition=analysis
#SBATCH --ntasks=1
#SBATCH --tasks-per-node=1
#SBATCH --time=48:00:00
#SBATCH --output=pism.%j
#SBATCH --mem=214G

cd $SLURM_SUBMIT_DIR

ulimit -l unlimited
ulimit -s unlimited
ulimit

export GDAL_DATA=/usr/local/pkg/data/GDAL/2.1.0-pic-intel-2016b/share/gdal

# Generated by /import/c1/ICESHEET/aaschwanden/pism-gris/stability/lhs_ensemble.py
# Command: ./lhs_ensemble.py -e ../latin_hypercube/lhs_control.csv --o_dir 2017_12_ctrl --exstep 1 -n 360 -w 168:00:00 -g 900 -s chinook -q t2standard --step 1000 --duration 2000 ../calibration/2017_06_vc/state/gris_g900m_flux_v3a_no_bath_sia_e_1.25_sia_n_3_ssa_n_3.25_ppq_0.6_tefo_0.02_calving_vonmises_calving_0_100.nc
# Git top level: /import/c1/ICESHEET/aaschwanden/pism-gris
# URL: git@github.com:pism/pism-gris.git
# Version: 0b9d042

# stop if a variable is not defined
set -u
# stop on errors
set -e

# path to the config file
config="/import/c1/ICESHEET/aaschwanden/pism-gris/stability/2017_12_ctrl/init_config.nc"
# path to the input directory (input data sets are contained in this directory)
input_dir="/import/c1/ICESHEET/aaschwanden/pism-gris"
# output directory
output_dir="/import/c1/ICESHEET/aaschwanden/pism-gris/stability/2017_12_ctrl"
# temporary directory for spatial files
spatial_tmp_dir="/import/c1/ICESHEET/aaschwanden/pism-gris/stability/2017_12_ctrl_tmp"

# create required output directories
for each in $output_dir/jobs $output_dir/basins $spatial_tmp_dir $output_dir/spatial $output_dir/scalar $output_dir/state $output_dir $output_dir/snap $output_dir/performance;
do
  mkdir -p $each
done

#adjust_timeline.py -i start -p yearly -a 2008-1-1 -u seconds -d 2008-1-1 $output_dir/scalar/ts_gris_g900m_v3a_rcp_26_id_CTRL_0_1000.nc 
#ncks -O -4 -L 3 $output_dir/state/gris_g900m_v3a_rcp_26_id_CTRL_0_1000.nc $output_dir/state/gris_g900m_v3a_rcp_26_id_CTRL_0_1000.nc 

#adjust_timeline.py -i start -p yearly -a 3008-1-1 -u seconds -d 2008-1-1 $output_dir/scalar/ts_gris_g900m_v3a_rcp_26_id_CTRL_1000_2000.nc 
#ncks -O -4 -L 3 $output_dir/state/gris_g900m_v3a_rcp_26_id_CTRL_1000_2000.nc $output_dir/state/gris_g900m_v3a_rcp_26_id_CTRL_1000_2000.nc 

#ncks -O -4 -L 3  $spatial_tmp_dir/ex_g900m_v3a_rcp_26_id_CTRL.nc $output_dir/spatial/ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
#adjust_timeline.py -i start -p yearly -a 2008-1-1 -u seconds -d 2008-1-1 $output_dir/spatial/ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
#~/base/gris-analysis/scripts/nc_add_hillshade.py -z 1  $output_dir/spatial/ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 

cd $output_dir/spatial 
#~/base/gris-analysis/basins/extract_basins.py --basins  CW --o_dir ../basins ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
~/base/gris-analysis/basins/extract_basins.py --basins  NE --o_dir ../basins ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
#~/base/gris-analysis/basins/extract_basins.py --basins  NO --o_dir ../basins ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
#~/base/gris-analysis/basins/extract_basins.py --basins  NW --o_dir ../basins ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
#~/base/gris-analysis/basins/extract_basins.py --basins  SE --o_dir ../basins ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
#~/base/gris-analysis/basins/extract_basins.py --basins  SW --o_dir ../basins ex_g900m_v3a_rcp_26_id_CTRL_0_2000.nc 
cd ../../ 
